# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'OnePartyGo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Fabric'
  pod 'Digits'
  pod 'Crashlytics'
  pod 'TwitterCore' 
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'CHRTextFieldFormatter'
  pod 'JGProgressHUD'
  pod 'ImagePicker'

# Pods for OnePartyGo

  target 'OnePartyGoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OnePartyGoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
