#! /bin/bash
rm ./app/design/adminhtml/default/wyomind/template/sales/order/creditmemo/create/items/renderer/ai-default.phtml
rm ./app/design/frontend/base/default/template/pickupatstore/checkout/onepage/shipping_method/available.phtml
rm ./app/design/frontend/base/default/template/pickupatstore/checkout/onepage/progress/shipping_method.phtml
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-upgrade-1.0.0-2.0.0.php
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-upgrade-5.0.1-5.1.0.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Pointofsale/Edit/Tab/Advancedinventory.php
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-upgrade-5.0.0-5.0.1.php
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-upgrade-2.0.0-3.0.0.php
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-upgrade-3.0.0-4.3.4.php
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-upgrade-4.3.4-5.0.0.php
rm ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field/Extensions.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Pointofsale/Edit/Tab/Renderer/Button.php
rm ./app/design/frontend/base/default/template/pickupatstore/persistent/checkout/onepage/billing.phtml
rm ./app/design/frontend/base/default/template/pickupatstore/checkout/onepage/progress/shipping.phtml
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-upgrade-3.8.0-3.9.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-upgrade-3.1.0-3.3.1.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-upgrade-3.4.0-3.4.1.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Catalog/Product/Edit/Tab/Inventory.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-upgrade-3.0.0-3.1.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-upgrade-3.7.0-3.8.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-upgrade-3.3.1-3.4.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-upgrade-3.4.1-3.7.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-upgrade-3.1.0-3.2.0.php
rmdir  ./app/design/adminhtml/default/wyomind/template/sales/order/creditmemo/create/items/renderer
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Catalog/Product/Renderer/Treeview.php
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-install-2.0.0.php
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-install-5.1.0.php
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-install-5.0.0.php
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-install-1.0.0.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Sales/Order/Renderer/Assignation.php
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-install-4.3.4.php
rm ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup/mysql4-install-3.0.0.php
rm ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field/Link.php
rmdir  ./app/design/frontend/base/default/template/pickupatstore/checkout/onepage/shipping_method
rm ./app/code/local/Wyomind/Advancedinventory/controllers/Adminhtml/Catalog/ProductController.php
rm ./app/design/adminhtml/default/wyomind/template/sales/order/creditmemo/create/ai-items.phtml
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Pointofsale/Edit/Tab/Renderer
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-install-3.9.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-install-3.8.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-install-3.1.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-install-3.4.1.php
rm ./app/code/local/Wyomind/Advancedinventory/Model/Resource/Eav/Mysql4/Product/Collection.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-install-3.3.1.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-install-3.2.0.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Stocks/Renderer/StoreViewQty.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-install-3.7.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-install-3.4.0.php
rm ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup/mysql4-install-1.0.0.php
rm ./app/code/local/Wyomind/Advancedinventory/controllers/Adminhtml/PermissionsController.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Stocks/Renderer/StockStatus.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/System/Config/Form/Field/Link.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field
rm ./app/code/local/Wyomind/Pointofsale/sql/pointofsale_setup/mysql4-upgrade-5.1.1-5.1.2.php
rmdir  ./app/design/frontend/base/default/template/pickupatstore/persistent/checkout/onepage
rm ./app/code/local/Wyomind/Pointofsale/sql/pointofsale_setup/mysql4-upgrade-5.3.0-5.4.0.php
rm ./app/design/frontend/base/default/template/advancedinventory/catalog/product/view.phtml
rm ./app/design/adminhtml/default/wyomind/template/catalog/product/tab/base-inventory.phtml
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Stocks/Renderer/GlobalQty.php
rm ./app/design/frontend/base/default/template/pickupatstore/checkout/onepage/billing.phtml
rm ./app/code/local/Wyomind/Pickupatstore/Block/Adminhtml/System/Config/Form/Field/Link.php
rmdir  ./app/design/adminhtml/default/wyomind/template/sales/order/creditmemo/create/items
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Catalog/Product/Edit/Tab
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/System/Config/Form/Field/Cron.php
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Catalog/Product/Renderer
rm ./app/code/local/Wyomind/Pickupatstore/sql/pickupatstore_setup/mysql4-install-2.0.0.php
rmdir  ./app/design/frontend/base/default/template/pickupatstore/checkout/onepage/progress
rm ./app/code/local/Wyomind/Pickupatstore/sql/pickupatstore_setup/mysql4-install-1.3.0.php
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Edit/Tab/Customergroup.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Pointofsale/Manage/Grid.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Pointofsale/Permissions.php
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/System/Config/Form/Field/Link.php
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Renderer/Customergroup.php
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/System/Config/Form/Field
rm ./app/code/local/Wyomind/Advancedinventory/controllers/Adminhtml/StocksController.php
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Edit/Tab/Informations.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Log/Renderer/Reference.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Stocks/Renderer/PosQty.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Stocks/Renderer/Action.php
rm ./app/code/local/Wyomind/Massstockupdate/controllers/Adminhtml/ImportsController.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Pointofsale/Edit/Tabs.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Tab/Mapping.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Tab/Setting.php
rmdir  ./app/code/local/Wyomind/Pickupatstore/Block/Adminhtml/System/Config/Form/Field
rm ./app/code/local/Wyomind/Pointofsale/sql/pointofsale_setup/mysql4-install-5.4.0.php
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Catalog/Product/Grid.php
rm ./app/code/local/Wyomind/Pointofsale/sql/pointofsale_setup/mysql4-install-5.1.2.php
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Import/Tab/Uploader.php
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Edit/Tab/Storeviews.php
rm ./app/code/local/Wyomind/Pointofsale/sql/pointofsale_setup/mysql4-install-5.0.0.php
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Sales/Order/Renderer
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Catalog/Product/Edit
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Pointofsale/Edit/Tab
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Renderer/Action.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form
rm ./app/code/local/Wyomind/Advancedinventory/controllers/Adminhtml/LogController.php
rm ./app/code/local/Wyomind/Advancedinventory/controllers/Adminhtml/PosController.php
rm ./app/code/local/Wyomind/Advancedinventory/Model/System/Config/Source/Statuses.php
rm ./app/code/community/Wyomind/Watchlog/controllers/Adminhtml/AdvancedController.php
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Renderer/Storeview.php
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/System/Config/Form/Field
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minusfull_over3.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minusfull_over4.gif
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Pointofsale/Manage
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minusfull_over5.gif
rmdir  ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/System/Config/Form/Field
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minusfull_over2.gif
rmdir  ./app/design/frontend/base/default/template/advancedinventory/catalog/product
rm ./app/code/community/Wyomind/Watchlog/sql/watchlog_setup/mysql4-install-1.0.0.php
rmdir  ./app/design/frontend/base/default/template/pickupatstore/persistent/checkout
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Tab/Cron.php
rmdir  ./app/design/adminhtml/default/wyomind/template/sales/order/creditmemo/create
rm ./app/code/local/Wyomind/Advancedinventory/Model/CatalogInventory/Stock/Item.php
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plusfull_over5.gif
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Edit/Tab/Address.php
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plusfull_over4.gif
rm ./app/code/local/Wyomind/Advancedinventory/Model/System/Config/Source/Stocks.php
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plusfull_over2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plusfull_over3.gif
rm ./app/code/local/Wyomind/Advancedinventory/Model/Resource/Product/Collection.php
rm ./app/design/adminhtml/default/wyomind/template/catalog/product/tab/stocks.phtml
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Resource/Eav/Mysql4/Product
rm ./app/code/local/Wyomind/Pointofsale/controllers/Adminhtml/ManageController.php
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Renderer/Action.php
rm ./app/code/community/Wyomind/Watchlog/controllers/Adminhtml/BasicController.php
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Pointofsale/Edit
rm ./app/design/adminhtml/default/wyomind/template/sales/order/view/tab/info.phtml
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/System/Config/Form
rm ./app/code/local/Wyomind/Advancedinventory/Model/System/Config/Source/Date.php
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Renderer/Order.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config
rm ./app/code/local/Wyomind/Advancedinventory/Model/System/Config/Source/Link.php
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Catalog/Product
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Renderer/Store.php
rmdir  ./app/design/frontend/base/default/template/pickupatstore/checkout/onepage
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Stocks/Renderer
rm ./skin/adminhtml/default/default/advancedinventory/images/minusfull_over3.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minus_over5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/minusfull_over5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minus_over2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minus_over4.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minus_over3.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/minusfull_over4.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_linebgfull2.gif
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Tabs.php
rm ./skin/adminhtml/default/default/advancedinventory/images/minusfull_over2.gif
rm ./app/design/adminhtml/default/wyomind/template/pointofsale/permissions.phtml
rm ./app/design/adminhtml/default/default/template/massstockupdate/mapping.phtml
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Form.php
rmdir  ./app/code/local/Wyomind/Pickupatstore/Block/Adminhtml/System/Config/Form
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plus_over4.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minusfull2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plus_over2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minusfull3.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minusfull5.gif
rmdir  ./app/code/local/Wyomind/Advancedinventory/controllers/Adminhtml/Catalog
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plus_over3.gif
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Notifications.php
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plus_over5.gif
rm ./app/code/local/Wyomind/Advancedinventory/Model/Mysql4/Stock/Collection.php
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_linebgfull.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minusfull4.gif
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/System/Config/Form
rm ./skin/adminhtml/default/default/advancedinventory/images/plusfull_over2.gif
rm ./app/code/local/Wyomind/Pointofsale/Model/Mysql4/Pointofsale/Collection.php
rm ./skin/adminhtml/default/default/advancedinventory/images/plusfull_over3.gif
rm ./app/design/frontend/base/default/template/pickupatstore/googlemap.js.phtml
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Renderer
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit/Tab
rm ./skin/adminhtml/default/default/advancedinventory/images/plusfull_over4.gif
rm ./app/code/local/Wyomind/Licensemanager/controllers/ActivationController.php
rm ./skin/adminhtml/default/default/advancedinventory/images/plusfull_over5.gif
rm ./app/design/adminhtml/default/default/template/watchlog/email/report.phtml
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plusfull3.gif
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Import/Tabs.php
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/CatalogInventory/Stock
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_linefull1.gif
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Log/Renderer
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Import/Form.php
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_linefull5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_linefull4.gif
rm ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/Import/Collection.php
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plusfull4.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_linefull0.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plusfull2.gif
rm ./app/code/local/Wyomind/Advancedinventory/Model/Mysql4/Item/Collection.php
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_linefull3.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_linefull2.gif
rmdir  ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/System/Config/Form
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plusfull5.gif
rm ./app/code/community/Wyomind/Watchlog/Model/Mysql4/Watchlog/Collection.php
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/System/Config
rmdir  ./app/code/local/Wyomind/Advancedinventory/sql/advancedinventory_setup
rmdir  ./app/design/adminhtml/default/wyomind/template/sales/order/creditmemo
rmdir  ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Import/Tab
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Stocks/Grid.php
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Pointofsale
rm ./app/code/local/Wyomind/Advancedinventory/Model/Mysql4/Log/Collection.php
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Sales/Order
rm ./app/design/adminhtml/default/default/template/massstockupdate/cron.phtml
rm ./skin/adminhtml/default/default/advancedinventory/images/check_over1.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/linebgfull2.gif
rm ./app/design/frontend/base/default/template/pointofsale/pointofsale.phtml
rmdir  ./app/design/frontend/base/default/template/advancedinventory/catalog
rm ./skin/adminhtml/default/default/advancedinventory/images/check_over3.gif
rm ./app/code/community/Wyomind/Watchlog/Model/System/Config/Source/Link.php
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_linebg2.gif
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/System/Config/Source
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Edit/Form.php
rm ./skin/adminhtml/default/default/advancedinventory/images/musicfolder.gif
rm ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/Notifications.php
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Renderer/Status.php
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Edit/Tabs.php
rm ./skin/adminhtml/default/default/advancedinventory/images/check_over2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/minus_over4.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/minus_over5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/minus_over3.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/minus_over2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/minus_over0.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/plus_over0.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minus4.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/plus_over5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minus2.gif
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minus5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/plus_over3.gif
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Resource/Eav/Mysql4
rm ./skin/adminhtml/default/default/advancedinventory/images/plus_over2.gif
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Edit.php
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import/Grid.php
rm ./skin/adminhtml/default/default/advancedinventory/images/plus_over4.gif
rm ./app/code/local/Wyomind/Advancedinventory/controllers/RssController.php
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_minus3.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_linebg.gif
rmdir  ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Edit/Tab
rm ./app/code/local/Wyomind/Pickupatstore/controllers/OnepageController.php
rmdir  ./app/design/frontend/base/default/template/pickupatstore/persistent
rm ./skin/adminhtml/default/default/advancedinventory/images/minusfull5.gif
rm ./app/design/adminhtml/default/wyomind/template/stocks/assignation.phtml
rm ./skin/adminhtml/default/default/advancedinventory/images/minusfull3.gif
rmdir  ./app/design/adminhtml/default/wyomind/template/sales/order/view/tab
rmdir  ./app/code/local/Wyomind/Pickupatstore/Block/Adminhtml/System/Config
rm ./skin/adminhtml/default/default/advancedinventory/images/folderopen.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/minusfull2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/linebgfull.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/minusfull4.gif
rmdir  ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Renderer
rm ./app/code/local/Wyomind/Advancedinventory/Model/Bundle/Product/Type.php
rm ./skin/adminhtml/default/default/advancedinventory/images/linefull0.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/plusfull4.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/linefull2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/imgfolder.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/plusfull5.gif
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System
rmdir  ./app/design/adminhtml/default/wyomind/template/catalog/product/tab
rm ./skin/adminhtml/default/default/advancedinventory/images/linefull1.gif
rm ./app/design/adminhtml/default/default/template/watchlog/advanced.phtml
rm ./skin/adminhtml/default/default/advancedinventory/images/plusfull2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/linefull3.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_line4.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_line5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plus3.gif
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Advanced/Grid.php
rm ./skin/adminhtml/default/default/advancedinventory/images/linefull4.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/plusfull3.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plus2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/linefull5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_line0.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_line1.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plus5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/trashfull.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_line3.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_line2.gif
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/System/Config
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Log/Grid.php
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_plus4.gif
rmdir  ./app/design/frontend/base/default/template/pickupatstore/checkout
rm ./app/design/adminhtml/default/wyomind/template/stocks/container.phtml
rmdir  ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/System/Config
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Catalog
rmdir  ./app/code/local/Wyomind/Massstockupdate/sql/massstockupdate_setup
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Import.php
rmdir  ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Import
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Renderer/Ip.php
rm ./app/code/local/Wyomind/Notificationmanager/Model/Resource/Setup.php
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Resource/Product
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Stocks.php
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Stocks
rm ./skin/adminhtml/default/default/advancedinventory/images/rtl_pt2.gif
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/CatalogInventory
rm ./skin/adminhtml/default/default/advancedinventory/images/linebg2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/check1.gif
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Grid.php
rm ./skin/adminhtml/default/default/advancedinventory/images/check3.gif
rmdir  ./app/design/adminhtml/default/wyomind/template/sales/order/view
rm ./app/design/adminhtml/default/default/template/watchlog/chart.phtml
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Edit.php
rm ./skin/adminhtml/default/default/advancedinventory/images/check2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/unlock.gif
rmdir  ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage/Edit
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Sales
rm ./skin/adminhtml/default/default/advancedinventory/images/minus2.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/minus5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/minus3.gif
rm ./app/design/adminhtml/default/default/template/watchlog/basic.phtml
rm ./skin/adminhtml/default/default/advancedinventory/images/minus4.gif
rmdir  ./app/code/community/Wyomind/Watchlog/Model/System/Config/Source
rm ./skin/adminhtml/default/default/advancedinventory/images/minus0.gif
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Basic/Grid.php
rm ./app/code/local/Wyomind/Pointofsale/controllers/IndexController.php
rm ./skin/adminhtml/default/default/advancedinventory/images/folder.gif
rmdir  ./app/code/local/Wyomind/Advancedinventory/controllers/Adminhtml
rm ./skin/adminhtml/default/default/advancedinventory/js/permissions.js
rm ./skin/adminhtml/default/default/advancedinventory/images/linebg.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/plus0.gif
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Bundle/Product
rm ./app/code/local/Wyomind/Massstockupdate/Helper/Massstockupdate.php
rm ./skin/adminhtml/default/default/advancedinventory/images/plus4.gif
rm ./app/code/local/Wyomind/Advancedinventory/Model/Paypal/Express.php
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/System
rm ./skin/adminhtml/default/default/advancedinventory/images/plus5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/line4.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/plus3.gif
rm ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import.php
rm ./skin/adminhtml/default/default/advancedinventory/images/line5.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/empty.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/plus2.gif
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml/Import
rm ./skin/adminhtml/default/default/advancedinventory/images/trash.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/line3.gif
rmdir  ./app/design/adminhtml/default/default/template/massstockupdate
rm ./skin/adminhtml/default/default/advancedinventory/images/line2.gif
rm ./skin/adminhtml/default/default/advancedinventory/css/treeview.css
rm ./skin/adminhtml/default/default/advancedinventory/images/line1.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/globe.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/line0.gif
rmdir  ./app/design/adminhtml/default/wyomind/template/catalog/product
rm ./skin/adminhtml/default/default/advancedinventory/images/watch.gif
rm ./app/design/adminhtml/default/wyomind/layout/advancedinventory.xml
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/System/Config
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Renderer
rmdir  ./app/design/adminhtml/default/default/template/watchlog/email
rm ./skin/adminhtml/default/default/advancedinventory/images/load.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/lock.gif
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Log
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Advanced.php
rm ./skin/adminhtml/default/default/advancedinventory/images/wait.gif
rm ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml/Log.php
rm ./skin/adminhtml/default/default/advancedinventory/images/page.gif
rm ./skin/adminhtml/default/default/advancedinventory/images/base.gif
rmdir  ./app/code/local/Wyomind/Massstockupdate/controllers/Adminhtml
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Advanced
rmdir  ./app/code/local/Wyomind/Pickupatstore/sql/pickupatstore_setup
rm ./skin/adminhtml/default/default/advancedinventory/js/treeview.js
rm ./app/code/local/Wyomind/Pointofsale/Model/Mysql4/Pointofsale.php
rm ./app/code/local/Wyomind/Advancedinventory/Helper/Permissions.php
rm ./skin/adminhtml/default/default/advancedinventory/css/styles.css
rm ./app/design/adminhtml/default/default/layout/massstockupdate.xml
rm ./skin/adminhtml/default/default/advancedinventory/images/pt2.gif
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Resource/Eav
rmdir  ./app/code/local/Wyomind/Pointofsale/Model/Mysql4/Pointofsale
rmdir  ./app/design/frontend/base/default/template/advancedinventory
rm ./app/code/local/Wyomind/Licensemanager/Helper/Licensemanager.php
rmdir  ./app/code/local/Wyomind/Pickupatstore/Block/Adminhtml/System
rm ./app/code/local/Wyomind/Advancedinventory/Model/Mysql4/Stock.php
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Mysql4/Stock
rm ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/Import.php
rm ./skin/adminhtml/default/default/advancedinventory/images/pt.gif
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/System
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml
rmdir  ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4/Import
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Mysql4/Item
rm ./app/design/adminhtml/default/default/layout/licensemanager.xml
rm ./skin/adminhtml/default/default/advancedinventory/js/scripts.js
rm ./app/code/local/Wyomind/Advancedinventory/Model/Mysql4/Item.php
rmdir  ./app/design/adminhtml/default/wyomind/template/pointofsale
rm ./app/design/frontend/base/default/layout/advancedinventory.xml
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Chart.php
rm ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Basic.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Resource
rm ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage.php
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml/Basic
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Mysql4/Log
rmdir  ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/Manage
rm ./app/code/local/Wyomind/Pickupatstore/Model/Carrier/Pickup.php
rm ./app/code/local/Wyomind/Advancedinventory/Model/Mysql4/Log.php
rm ./app/code/local/Wyomind/Notificationmanager/Model/Observer.php
rm ./app/code/community/Wyomind/Watchlog/Model/Mysql4/Watchlog.php
rmdir  ./app/code/community/Wyomind/Watchlog/controllers/Adminhtml
rmdir  ./app/code/community/Wyomind/Watchlog/Model/Mysql4/Watchlog
rm ./app/code/local/Wyomind/Advancedinventory/Model/Paypal/Ipn.php
rmdir  ./app/design/adminhtml/default/wyomind/template/sales/order
rmdir  ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml/System
rm ./skin/frontend/base/default/pointofsale/images/ajax-loader.gif
rmdir  ./app/code/local/Wyomind/Pointofsale/controllers/Adminhtml
rm ./app/code/local/Wyomind/Notificationmanager/etc/adminhtml.xml
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Adminhtml
rmdir  ./app/code/local/Wyomind/Pointofsale/sql/pointofsale_setup
rm ./app/code/local/Wyomind/Advancedinventory/Block/Rss/Stock.php
rm ./app/code/local/Wyomind/Advancedinventory/Model/Observer.php
rm ./skin/frontend/base/default/advancedinventory/css/stocks.css
rm ./app/design/adminhtml/default/default/layout/pointofsale.xml
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Resource
rmdir  ./app/code/community/Wyomind/Watchlog/Model/System/Config
rmdir  ./app/design/frontend/base/default/template/pickupatstore
rmdir  ./skin/adminhtml/default/default/advancedinventory/images
rmdir  ./app/design/adminhtml/default/default/template/watchlog
rm ./skin/frontend/base/default/pointofsale/css/pointofsale.css
rmdir  ./app/code/community/Wyomind/Watchlog/sql/watchlog_setup
rm ./app/code/local/Wyomind/Notificationmanager/Helper/Data.php
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block/Adminhtml
rm ./skin/adminhtml/default/default/massstockupdate/import.css
rm ./app/design/frontend/base/default/layout/pickupatstore.xml
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Bundle
rm ./app/code/local/Wyomind/Advancedinventory/Block/Stocks.php
rmdir  ./app/design/frontend/base/default/template/pointofsale
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/System
rmdir  ./app/design/adminhtml/default/wyomind/template/catalog
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Paypal
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model/Mysql4
rm ./app/code/local/Wyomind/Pointofsale/Helper/Pointofsale.php
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml
rm ./app/code/local/Wyomind/Massstockupdate/Model/Observer.php
rm ./app/code/local/Wyomind/Notificationmanager/etc/config.xml
rm ./app/code/local/Wyomind/Notificationmanager/etc/system.xml
rmdir  ./app/code/local/Wyomind/Advancedinventory/controllers
rm ./app/code/local/Wyomind/Pointofsale/Model/Pointofsale.php
rm ./app/code/local/Wyomind/Advancedinventory/Helper/Data.php
rm ./app/design/adminhtml/default/default/layout/watchlog.xml
rm ./app/code/local/Wyomind/Licensemanager/Model/Observer.php
rm ./app/code/local/Wyomind/Advancedinventory/Model/Stock.php
rm ./app/code/local/Wyomind/Pointofsale/Block/Pointofsale.php
rmdir  ./app/code/local/Wyomind/Pickupatstore/Block/Adminhtml
rmdir  ./skin/adminhtml/default/default/advancedinventory/css
rm ./skin/adminhtml/default/default/massstockupdate/import.js
rm ./skin/frontend/base/default/pointofsale/js/pointofsale.js
rmdir  ./app/design/adminhtml/default/wyomind/template/stocks
rmdir  ./skin/adminhtml/default/default/advancedinventory/js
rm ./app/code/local/Wyomind/Advancedinventory/etc/system.xml
rmdir  ./app/code/community/Wyomind/Watchlog/Block/Adminhtml
rmdir  ./app/design/adminhtml/default/wyomind/template/sales
rm ./app/code/local/Wyomind/Advancedinventory/etc/config.xml
rmdir  ./app/code/local/Wyomind/Massstockupdate/Model/Mysql4
rm ./app/code/local/Wyomind/Massstockupdate/Model/Import.php
rm ./app/code/local/Wyomind/Advancedinventory/Helper/Log.php
rm ./app/code/local/Wyomind/Advancedinventory/Model/Item.php
rm ./app/code/local/Wyomind/Pickupatstore/Model/Observer.php
rm ./app/design/frontend/base/default/layout/pointofsale.xml
rmdir  ./app/code/local/Wyomind/Pointofsale/Block/Adminhtml
rmdir  ./app/code/local/Wyomind/Massstockupdate/controllers
rmdir  ./app/code/local/Wyomind/Pickupatstore/Model/Carrier
rm ./app/code/local/Wyomind/Advancedinventory/Model/Api.php
rm ./app/code/community/Wyomind/Watchlog/Model/Observer.php
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block/Rss
rm ./app/code/local/Wyomind/Massstockupdate/Helper/Data.php
rm ./app/code/local/Wyomind/Advancedinventory/Model/Log.php
rm ./app/code/community/Wyomind/Watchlog/Model/Watchlog.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Helper
rm ./app/code/local/Wyomind/Massstockupdate/etc/config.xml
rm ./app/code/local/Wyomind/Licensemanager/Helper/Data.php
rm ./skin/frontend/base/default/pickupatstore/js/script.js
rmdir  ./app/code/local/Wyomind/Licensemanager/controllers
rm ./app/code/local/Wyomind/Massstockupdate/etc/system.xml
rmdir  ./skin/frontend/base/default/advancedinventory/css
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model
rmdir  ./app/code/community/Wyomind/Watchlog/Model/Mysql4
rm ./app/code/local/Wyomind/Advancedinventory/etc/api.xml
rmdir  ./skin/adminhtml/default/default/advancedinventory
rm ./app/locale/en_US/template/email/watchlog_report.html
rm ./app/code/local/Wyomind/Pickupatstore/Helper/Data.php
rmdir  ./app/code/local/Wyomind/Pickupatstore/controllers
rm ./app/code/local/Wyomind/Licensemanager/etc/config.xml
rmdir  ./app/code/community/Wyomind/Watchlog/Model/System
rm ./app/code/local/Wyomind/Pickupatstore/etc/system.xml
rmdir  ./app/code/community/Wyomind/Watchlog/controllers
rmdir  ./app/code/local/Wyomind/Advancedinventory/Helper
rm ./app/code/local/Wyomind/Pickupatstore/etc/config.xml
rm ./app/code/community/Wyomind/Watchlog/Helper/Data.php
rmdir  ./app/code/local/Wyomind/Pointofsale/Model/Mysql4
rmdir  ./app/code/local/Wyomind/Advancedinventory/Block
rm ./app/code/community/Wyomind/Watchlog/etc/config.xml
rmdir  ./skin/adminhtml/default/default/massstockupdate
rm ./app/code/local/Wyomind/Pointofsale/Helper/Data.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/etc
rmdir  ./app/code/local/Wyomind/Advancedinventory/Model
rm ./app/code/community/Wyomind/Watchlog/etc/system.xml
rmdir  ./app/code/local/Wyomind/Pointofsale/controllers
rmdir  ./app/design/adminhtml/default/default/template
rmdir  ./app/design/adminhtml/default/wyomind/template
rmdir  ./skin/frontend/base/default/pointofsale/images
rm ./app/code/local/Wyomind/Pointofsale/etc/system.xml
rmdir  ./app/code/local/Wyomind/Massstockupdate/Helper
rm ./app/code/local/Wyomind/Pointofsale/etc/config.xml
rmdir  ./app/code/local/Wyomind/Advancedinventory/etc
rmdir  ./app/code/local/Wyomind/Massstockupdate/Model
rmdir  ./app/code/local/Wyomind/Licensemanager/Helper
rmdir  ./skin/frontend/base/default/advancedinventory
rmdir  ./app/code/local/Wyomind/Massstockupdate/Block
rmdir  ./app/code/local/Wyomind/Advancedinventory/sql
rmdir  ./app/code/local/Wyomind/Licensemanager/Model
rmdir  ./app/design/adminhtml/default/wyomind/layout
rmdir  ./skin/frontend/base/default/pickupatstore/js
rm ./app/etc/modules/Wyomind_Notificationmanager.xml
rm ./tools/api/Advancedinventory-apicall.php.example
rmdir  ./app/code/local/Wyomind/Pickupatstore/Helper
rmdir  ./app/design/adminhtml/default/default/layout
rmdir  ./app/code/local/Wyomind/Licensemanager/Block
rmdir  ./app/code/local/Wyomind/Massstockupdate/etc
rmdir  ./app/code/local/Wyomind/Pickupatstore/Block
rmdir  ./app/code/local/Wyomind/Notificationmanager
rmdir  ./app/code/local/Wyomind/Pickupatstore/Model
rmdir  ./app/code/local/Wyomind/Massstockupdate/sql
rm ./app/locale/en_US/Wyomind_Advancedinventory.csv
rm ./app/locale/fr_FR/Wyomind_Advancedinventory.csv
rmdir  ./skin/frontend/base/default/pointofsale/css
rmdir  ./app/code/community/Wyomind/Watchlog/Helper
rmdir  ./app/code/local/Wyomind/Pointofsale/Helper
rmdir  ./app/code/community/Wyomind/Watchlog/Block
rmdir  ./app/code/local/Wyomind/Licensemanager/etc
rmdir  ./app/design/frontend/base/default/template
rmdir  ./skin/frontend/base/default/pointofsale/js
rm ./app/etc/modules/Wyomind_Advancedinventory.xml
rmdir  ./app/code/community/Wyomind/Watchlog/Model
rmdir  ./app/code/local/Wyomind/Pointofsale/Model
rmdir  ./skin/frontend/base/default/pickupatstore
rmdir  ./app/code/local/Wyomind/Pickupatstore/sql
rmdir  ./app/code/local/Wyomind/Pointofsale/Block
rmdir  ./app/code/local/Wyomind/Pickupatstore/etc
rmdir  ./app/code/local/Wyomind/Advancedinventory
rmdir  ./app/code/community/Wyomind/Watchlog/sql
rmdir  ./app/design/frontend/base/default/layout
rmdir  ./app/code/community/Wyomind/Watchlog/etc
rm ./app/etc/modules/Wyomind_Massstockupdate.xml
rmdir  ./skin/frontend/base/default/pointofsale
rmdir  ./app/code/local/Wyomind/Massstockupdate
rm ./app/locale/fr_FR/Wyomind_Pickupatstore.csv
rmdir  ./app/code/local/Wyomind/Pointofsale/sql
rm ./app/etc/modules/Wyomind_Licensemanager.xml
rmdir  ./app/code/local/Wyomind/Pointofsale/etc
rm ./app/locale/en_US/Wyomind_Pickupatstore.csv
rm ./app/locale/da_DK/Wyomind_Pickupatstore.csv
rm ./app/etc/modules/Wyomind_Pickupatstore.xml
rmdir  ./app/code/local/Wyomind/Licensemanager
rm ./app/locale/en_US/Wyomind_Pointofsale.csv
rm ./app/locale/de_DE/Wyomind_Pointofsale.csv
rmdir  ./app/code/local/Wyomind/Pickupatstore
rmdir  ./app/design/adminhtml/default/default
rmdir  ./app/design/adminhtml/default/wyomind
rm ./app/locale/fr_FR/Wyomind_Pointofsale.csv
rm ./app/etc/modules/Wyomind_Localstores.xml
rm ./app/etc/modules/Wyomind_Pointofsale.xml
rmdir  ./app/code/community/Wyomind/Watchlog
rm ./lib/Varien/Data/Form/Element/Hours.php
rmdir  ./app/code/local/Wyomind/Pointofsale
rm ./var/backups/stockupdater-demofile.csv
rm ./lib/Varien/Data/Form/Element/Link.php
rmdir  ./app/design/frontend/base/default
rm ./app/etc/modules/Wyomind_Watchlog.xml
rmdir  ./app/locale/en_US/template/email
rmdir  ./skin/adminhtml/default/default
rmdir  ./lib/Varien/Data/Form/Element
rmdir  ./app/design/adminhtml/default
rmdir  ./app/code/community/Wyomind
rmdir  ./skin/frontend/base/default
rmdir  ./app/locale/en_US/template
rmdir  ./app/design/frontend/base
rm ./tools/sh/MassStockUpdate.sh
rmdir  ./skin/adminhtml/default
rmdir  ./app/code/local/Wyomind
rmdir  ./lib/Varien/Data/Form
rmdir  ./app/design/adminhtml
rmdir  ./app/design/frontend
rmdir  ./skin/frontend/base
rmdir  ./app/code/community
rmdir  ./app/locale/da_DK
rmdir  ./app/locale/en_US
rmdir  ./app/locale/de_DE
rmdir  ./app/locale/fr_FR
rmdir  ./lib/Varien/Data
rmdir  ./app/etc/modules
rmdir  ./app/code/local
rmdir  ./skin/adminhtml
rmdir  ./skin/frontend
rmdir  ./var/backups
rmdir  ./lib/Varien
rmdir  ./app/locale
rmdir  ./app/design
rmdir  ./tools/api
rmdir  ./tools/sh
rmdir  ./app/code
rmdir  ./app/etc
rmdir  ./tools
rmdir  ./skin
rmdir  ./var
rmdir  ./app
rmdir  ./lib